theme = "ivy"
baseURL = 'http://neilchen863.github.io/'
languageCode = 'en-us'
title = 'Isoland'


disqusShortname = "Neil"
hasCJKLanguage = true
enableEmoji = true
footnotereturnlinkcontents = "↩"

#[permalinks]
#posts = "/"
#newsletter = ""
#journal = ""

[menu]
[[menu.main]]
name="电影 | Film"
url="/film/"
weight="1"
[[menu.main]]
name="书目 | Book"
url="/book/"
weight="2"
[[menu.main]]
name="生活 | Life"
url="/life/"
weight="3"
[[menu.main]]
name="技术 | Tech"
url="/tech/"
weight="4"


[params]
description = "I wanted to live deep and suck out all the marrow of life, to drive life into a corner, and reduce it to its lowest terms."
footer = "&copy; [Neil](https://neilchen863.github.io) | since 2024"
highlightjsCDN = "//cdn.bootcss.com"
highlightjsLang = ["r", "yaml", "tex"]
highlightjsTheme = "github"
highlightjsVersion = "9.12.0"
customCSS = ["themes/ivy/static/css/custom.css"]


[params.twikoo]
enable = true

[blackfriday]
extensionsmask = [ "noIntraEmphasis" ]
fractions = false

[markup.highlight]
codeFences = false

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.parser]
autoHeadingIDType = "blackfriday"

[markup.tableOfContents]
startLevel = 1
